# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Feb  7 15:50:47 2025
# ------------------------------------------------

package:
  name: tqdm
  version: 4.67.1
source:
  sha256: f8aef9c52c08c13a65f30ea34f4e5aac3fd1a34959879d7e59e63027286627f2
  url: https://pypi.io/packages/source/t/tqdm/tqdm-4.67.1.tar.gz
build:
  entry_points:
    - tqdm = tqdm.cli:main
  number: '0'
  script: /croot/tqdm_1738943501192/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h7040dfc_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - packaging 24.2 py313h06a4308_0
    - pip 24.2 py313h06a4308_0
    - python 3.13.2 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.8.0 py313h06a4308_0
    - setuptools-scm 8.1.0 py313h06a4308_0
    - setuptools_scm 8.1.0 hd3eb1b0_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.44.0 py313h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
  run_constrained:
    - ipywidgets >=6
test:
  commands:
    - pip check
    - tqdm --help
    - tqdm -v | rg 4.67.1
    - pytest -k "not tests_perf"
  imports:
    - tqdm
  requires:
    - dask-core
    - numpy
    - pandas
    - pip
    - pytest >=6
    - pytest-asyncio >=0.24
    - pytest-timeout
    - pytest-xdist
    - rich
    - ripgrep
  source_files:
    - pyproject.toml
    - tests
about:
  description: A Fast, Extensible Progress Bar for Python and CLI
  dev_url: https://github.com/tqdm/tqdm
  doc_url: https://tqdm.github.io/
  home: https://tqdm.github.io/
  license: MPL-2.0 AND MIT
  license_family: MOZILLA
  license_file: LICENCE
  summary: A Fast, Extensible Progress Meter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a76dc7cb-cf07-43c0-a8de-f74b44c95703
  recipe-maintainers:
    - casperdcl
    - pmlandwehr
  remote_url: git@github.com:AnacondaRecipes/tqdm-feedstock.git
  sha: 94cf0819d934b0cb8c4149ff64bbbbaad80b9ea0
