# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Mon Jan 27 15:03:21 2025
# ------------------------------------------------

package:
  name: wheel
  version: 0.45.1
source:
  sha256: 661e1abd9198507b1409a20c02106d9670b2576e916d58f520316666abca6729
  url: https://pypi.io/packages/source/w/wheel/wheel-0.45.1.tar.gz
build:
  entry_points:
    - wheel = wheel.cli:main
  number: '0'
  string: py39h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2024.12.31 h06a4308_0
    - flit-core 3.9.0 py39hee27c6d_1
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - python 3.9.21 he870216_1
    - python-installer 0.7.0 pyhd3eb1b0_1
    - readline 8.2 h5eee18b_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2025a h04d1e81_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.9,<3.10.0a0
test:
  commands:
    - pip check
    - wheel --help
    - wheel version
  imports:
    - wheel
    - wheel.cli
    - wheel.vendored
    - wheel.vendored.packaging
  requires:
    - pip
about:
  description: "This library is the reference implementation of the Python wheel packaging\
    \ standard,\nas defined in PEP 427.\nIt has two different roles:\n  1. A setuptools\
    \ extension for building wheels that provides the bdist_wheel setuptools command\n\
    \  2. A command line tool for working with wheel files\n"
  dev_url: https://github.com/pypa/wheel
  doc_url: https://wheel.readthedocs.io/
  home: https://github.com/pypa/wheel
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A built-package format for Python.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 38e9cb0e-93b6-4b39-afbd-cc5b2e3ec4a4
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/wheel-feedstock.git
  sha: 64951c61a61d8545134c0fb3cc217448d7b3573c
  skip-lints:
    - missing_wheel
