# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jan 10 23:01:57 2025
# ------------------------------------------------

package:
  name: truststore
  version: 0.10.0
source:
  fn: truststore-0.10.0.tar.gz
  sha256: 12e89641dba78a9427f782ad2d824bed93583a9465002fe59b63c3fd12cbe8f5
  url: https://github.com/sethmlarson/truststore/archive/refs/tags/v0.10.0.tar.gz
build:
  number: '0'
  script: /croot/truststore_1736550121485/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.12.31 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - flit-core 3.9.0 py313hee27c6d_1
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py313h06a4308_0
    - python 3.13.1 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.44.0 py313h06a4308_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest -v -s -rs --no-flaky-report --max-runs=3 tests/
  imports:
    - truststore
  requires:
    - aiohttp
    - flaky
    - httpx
    - pip
    - pyopenssl
    - pytest
    - pytest-asyncio
    - pytest-httpserver
    - requests
    - trustme
    - urllib3
  source_files:
    - tests
about:
  description: "A library which exposes native system certificate stores (ie \u201C\
    trust stores\u201D)\nthrough an ssl.SSLContext-like API. This means that Python\
    \ applications no\nlonger need to rely on certifi as a root certificate store.\n"
  dev_url: https://github.com/sethmlarson/truststore
  doc_url: https://truststore.readthedocs.io/
  home: https://github.com/sethmlarson/truststore
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Verify certificates using native system trust stores
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 10722e2b-be96-42b8-99d8-25bed2956809
  recipe-maintainers:
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/truststore-feedstock.git
  sha: 54e19d1b31e86cb72438537bf2fd45b4c0d3ef6b
