# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: libmpdec
  version: 4.0.0
source:
  patches:
    - fix-dll-name.diff
  sha256: 942445c3245b22730fd41a67a7c5c231d11cb1b9936b9c0f76334fb7d0b4468c
  url: https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.0.tar.gz
build:
  noarch: false
  noarch_python: false
  number: '0'
  string: h5eee18b_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.38 h2a08ee3_1
    - binutils_linux-64 2.38.0 hc2dff05_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.38 h1181459_1
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - test -f ${PREFIX}/lib/libmpdec.so.4
    - test -f ${PREFIX}/lib/libmpdec.so.4.0.0
about:
  description: 'libmpdec is a fast C library for correctly-rounded arbitrary precision
    decimal floating point

    arithmetic. It is a complete implementation of Mike Cowlishaw/IBM''s

    General Decimal Arithmetic Specification.

    '
  dev_url: https://www.bytereef.org/mpdecimal/download.html
  doc_url: https://www.bytereef.org/mpdecimal/index.html
  home: https://www.bytereef.org/mpdecimal/index.html
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYRIGHT.txt
  summary: A package for correctly-rounded arbitrary precision decimal floating point
    arithmetic
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 47159f3f-ead9-4457-8688-3a1b58fefb0c
  recipe-maintainers:
    - isuruf
  remote_url: git@github.com:AnacondaRecipes/mpdecimal-feedstock.git
  sha: 765d0b3f93bd70305a5e61c91a167ceab6b93428
