# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /work/perseverance-python-buildout/aggregate/distro-feedstock/recipe, last modified Tue Oct  8 10:19:18 2024
# ------------------------------------------------

package:
  name: distro
  version: 1.9.0
source:
  fn: distro-1.9.0.tar.gz
  sha256: 2fa77c6fd8940f116ee1d6b94a2f90b13b5ea8d019b98bc8bafdcabcdd9bdbed
  url: https://pypi.io/packages/source/d/distro/distro-1.9.0.tar.gz
build:
  entry_points:
    - distro = distro.distro:main
  number: '0'
  script: /work/perseverance-python-buildout/croot/distro_1728396110052/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -v --no-build-isolation
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2024.9.24 h06a4308_0
    - expat 2.6.3 h6a678d5_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.15 h5eee18b_0
    - pip 24.2 py313h06a4308_0
    - python 3.13.0 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.1.0 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - tzdata 2024b h04d1e81_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - distro --help
  imports:
    - distro
  requires:
    - pip
about:
  description: distro provides information about the OS distribution it runs on, such
    as a reliable machine-readable ID, or version information.
  dev_url: https://github.com/python-distro/distro
  doc_url: https://distro.readthedocs.io
  home: https://github.com/python-distro/distro
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A much more elaborate replacement for removed Python's 'platform.linux_distribution()'
    method
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - abloemert
    - windelbouwman
