# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Apr 29 20:31:15 2025
# ------------------------------------------------

package:
  name: xorg-libxau
  version: 1.0.12
source:
  sha256: 74d0e4dfa3d39ad8939e99bda37f5967aba528211076828464d2777d477fc0fb
  url: https://www.x.org/releases/individual/lib/libXau-1.0.12.tar.xz
build:
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - xorg-libxau >=1.0.12,<2.0a0
  string: h9b100fa_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - gettext 0.21.0 hedfda30_2
    - icu 73.1 h6a678d5_0
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libxml2 2.13.8 hfdd30dd_0
    - make 4.2.1 h1bed415_1
    - ncurses 6.4 h6a678d5_0
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - xorg-util-macros 1.19.0 h27cfd23_2
    - xorg-xorgproto 2024.1 h5eee18b_0
  run:
    - libgcc-ng >=11.2.0
test:
  commands:
    - test -f $PREFIX/include/X11/Xauth.h
    - test -f $PREFIX/lib/libXau.so
about:
  dev_url: https://gitlab.freedesktop.org/xorg/lib/libxau
  doc_url: https://gitlab.freedesktop.org/xorg/lib/libxau
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: A simple X Windows authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f1453058-fbf7-4955-b88f-ce0bb797ff7d
  recipe-maintainers:
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/xorg-libxau-feedstock.git
  sha: 2abcd0007b52cf8f5e9a2d4a34075cd7d187e3c4
