# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Jul 15 22:01:06 2025
# ------------------------------------------------

package:
  name: krb5
  version: 1.21.3
source:
  sha256: 2157d92020d408ed63ebcd886a92d1346a1383b0f91123a0473b4f69b4a24861
  url: https://github.com/krb5/krb5/archive/krb5-1.21.3-final.tar.gz
build:
  ignore_run_exports:
    - libstdcxx-ng
    - tk
  number: '1'
  run_exports:
    - krb5 >=1.21.3,<1.22.0a0
  string: h8a1dbc1_1
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - autoconf 2.71 pl5340h5eee18b_0
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - bison 3.7.5 h2531618_1
    - flex 2.6.4 ha10e3a4_1
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_2
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - m4 1.4.18 h4e445db_0
    - make 4.2.1 h1bed415_1
    - perl 5.40.2 0_h5eee18b_perl5
    - pkg-config 0.29.2 h1bed415_8
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - ca-certificates 2025.2.25 h06a4308_0
    - libedit 3.1.20221030 h5eee18b_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - zlib 1.2.13 h5eee18b_1
  run:
    - __glibc >=2.17,<3.0.a0
    - libedit >=3.1.20221030,<3.2.0a0
    - libedit >=3.1.20221030,<4.0a0
    - libgcc-ng >=11.2.0
    - openssl >=3.0.16,<4.0a0
test:
  requires:
    - python 3.11.*
about:
  description: 'Kerberos is a network authentication protocol. It is designed to provide
    strong authentication for client/server applications by using secret-key cryptography.

    '
  dev_url: https://github.com/krb5/krb5
  doc_url: https://web.mit.edu/kerberos/krb5-1.21/doc/index.html
  home: https://web.mit.edu/kerberos/
  license: MIT
  license_family: MIT
  license_file: doc/notice.rst
  summary: A network authentication protocol.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ea213c58-0034-484e-a488-0ca66cdcd02b
  recipe-maintainers:
    - chenghlee
    - mariusvniekerk
    - mingwandroid
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/krb5-feedstock.git
  sha: 788b3336e5953982ebd353f0b4104e36b2f23a45
