python:
  - 3.13
python_impl:
  - cpython
numpy:
  - 1.26
gil_type:
  - normal
  # Will be enabled as part of https://anaconda.atlassian.net/browse/PKG-5855
  # - disabled # [not (s390x or (osx and x86_64))]
