# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Thu Apr 10 08:17:17 2025
# ------------------------------------------------

package:
  name: platformdirs
  version: 4.3.7
source:
  sha256: eb437d586b6a0986388f0d6f74aa0cde27b48d0e3d66843640bfb6bdcdb6e351
  url: https://pypi.io/packages/source/p/platformdirs/platformdirs-4.3.7.tar.gz
build:
  number: '0'
  script: /croot/platformdirs_1744273042065/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --no-build-isolation -vv
  string: py313h06a4308_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h5eee18b_6
    - ca-certificates 2025.2.25 h06a4308_0
    - expat 2.6.4 h6a678d5_0
    - hatch-vcs 0.4.0 py313h06a4308_0
    - hatchling 1.27.0 py313h06a4308_0
    - ld_impl_linux-64 2.40 h12ee557_0
    - libffi 3.4.4 h6a678d5_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libmpdec 4.0.0 h5eee18b_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - packaging 24.2 py313h06a4308_0
    - pathspec 0.10.3 py313h06a4308_0
    - pip 25.0 py313h06a4308_0
    - pluggy 1.5.0 py313h06a4308_0
    - python 3.13.2 hf623796_100_cp313
    - python_abi 3.13 0_cp313
    - readline 8.2 h5eee18b_0
    - setuptools 75.8.0 py313h06a4308_0
    - setuptools-scm 8.2.1 py313h06a4308_0
    - sqlite 3.45.3 h5eee18b_0
    - tk 8.6.14 h39e8969_0
    - trove-classifiers 2024.10.14 py313h06a4308_0
    - tzdata 2025a h04d1e81_0
    - wheel 0.45.1 py313h06a4308_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - python >=3.13,<3.14.0a0
    - python_abi 3.13.* *_cp313
test:
  commands:
    - pip check
    - pytest tests -vv
  imports:
    - platformdirs
  requires:
    - appdirs
    - pip
    - pytest
    - pytest-mock
  source_files:
    - tests
about:
  description: 'About A small Python module for determining appropriate

    platform-specific dirs, e.g. a "user data dir".

    '
  dev_url: https://github.com/platformdirs/platformdirs
  doc_url: https://platformdirs.readthedocs.io/
  home: https://github.com/platformdirs/platformdirs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small Python module for determining appropriate platform-specific dirs,
    e.g. a "user data dir".
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd69721a-4b5d-4d72-a02e-6d7e90874ebe
  recipe-maintainers:
    - adament
    - gaborbernat
  remote_url: git@github.com:AnacondaRecipes/platformdirs-feedstock.git
  sha: 74dde69daa490954c24a50d26eb310a6c21a735d
