# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: libcurl
  version: 8.14.1
source:
  sha256: 5760ed3c1a6aac68793fc502114f35c3e088e8cd5c084c2d044abdf646ee48fb
  url: https://curl.se/download/curl-8.14.1.tar.bz2
build:
  number: 0
  run_exports:
    - libcurl >=8.14.1,<9.0a0
  string: h31d0fb7_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_2
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_2
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - c-ares 1.19.1 h5eee18b_0
    - ca-certificates 2025.2.25 h06a4308_0
    - krb5 1.21.3 h143b758_0
    - libedit 3.1.20230828 h5eee18b_0
    - libev 4.33 h7f8727e_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libnghttp2 1.57.0 h2d74bed_0
    - libssh2 1.11.1 h251f7ec_0
    - libstdcxx-ng 11.2.0 h1234567_1
    - lz4-c 1.9.4 h6a678d5_1
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.16 h5eee18b_0
    - xz 5.6.4 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
    - zstd 1.5.6 hc292b87_0
  run:
    - krb5 >=1.21.3,<1.22.0a0
    - libgcc-ng >=11.2.0
    - libnghttp2 >=1.57.0
    - libnghttp2 >=1.57.0,<2.0a0
    - libssh2 >=1.10.0
    - libssh2 >=1.11.1,<2.0a0
    - openssl >=3.0.16,<4.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.6,<1.6.0a0
test:
  commands:
    - curl-config --features
    - curl-config --protocols
    - test -f ${PREFIX}/lib/libcurl${SHLIB_EXT}
    - CURL_SSL_BACKENDS=$(curl-config --ssl-backends)
    - if ! echo $CURL_SSL_BACKENDS | grep -q "OpenSSL"; then exit 1; fi
about:
  description: 'Curl is an open source command line tool and library for transferring
    data

    with URL syntax. It is used in command lines or scripts to transfer data.

    '
  dev_url: https://github.com/curl/curl
  doc_url: https://curl.se/docs/
  home: https://curl.se/
  license: curl
  license_family: MIT
  license_url: https://curl.se/docs/copyright.html
  summary: tool and library for transferring data with URL syntax
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0f1eccb6-6331-436b-bfe6-feb5946d1820
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - xylar
  remote_url: git@github.com:AnacondaRecipes/curl-feedstock.git
  sha: 5b5c3841147d3233cfcb2081c4740296b00e9bbe
