# This file created by conda-build 24.1.2
# ------------------------------------------------

package:
  name: ld_impl_linux-64
  version: '2.40'
source:
  - folder: binutils
    patches:
      - patches/binutils/0000-sh-conf.patch
      - patches/binutils/0001-check_ldrunpath_length.patch
      - patches/binutils/0002-MinGW-w64-winpthreads-doesnt-have-pthread_mutexattr_settype.patch
      - patches/binutils/0003-Dont-link-to-libfl-as-its-unnecessary.patch
      - patches/binutils/0004-Darwin-gold-binary-cc-include-string-not-cstring.patch
      - patches/binutils/0005-Darwin-Two-fixes-from-Android-NDK-PTHREAD_ONCE_INIT-wcsncasecmp.patch
      - patches/binutils/0006-sysroot.patch
      - patches/binutils/0007-poison-system-directories.patch
      - patches/binutils/0009-fix-align-kernel.patch
    sha256: 0f8a4c272d7f17f369ded10a4aca28b8e304828e95526da482b0ccc4dfc9d8e1
    url: https://ftp.gnu.org/gnu/binutils/binutils-2.40.tar.xz
build:
  detect_binary_files_with_prefix: false
  merge_build_host: false
  missing_dso_whitelist:
    - '*'
  number: 0
  string: h12ee557_0
requirements:
  build: []
  run: []
  run_constrained:
    - binutils_impl_linux-64 2.40
test:
  commands:
    - x86_64-conda_cos7-linux-gnu-ld --help
    - echo "conda"
    - echo 11.2.0
about:
  dev_url: https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git
  home: https://www.gnu.org/software/binutils/
  license: GPL-3.0-only
  license_file:
    - binutils/COPYING
    - binutils/COPYING.LIB
    - binutils/COPYING3
    - binutils/COPYING3.LIB
  summary: 'A set of programming tools for creating and managing binary programs,
    object files,

    libraries, profile data, and assembly source code.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 55810a01-7546-4163-92b2-7788d3a1c21c
  recipe-maintainers:
    - katietz
  remote_url: git@github.com:AnacondaRecipes/binutils-feedstock.git
  sha: f23ead94cbf89b8fd758c4c8ef84aec43fa21a86
