# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# /feedstock/recipe, last modified Wed Oct  9 15:15:47 2024
# ------------------------------------------------

package:
  name: zstd
  version: 1.5.6
source:
  patches:
    - patches/4019.patch
  sha256: 30f35f71c1203369dc979ecde0400ffea93c27391bfd2ac5a9715d2173d92ff7
  url: https://github.com/facebook/zstd/archive/v1.5.6.tar.gz
build:
  number: '0'
  run_exports:
    - zstd >=1.5.6,<1.6.0a0
  string: hc292b87_0
requirements:
  build:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - _sysroot_linux-64_curr_repodata_hack 3 haa98f57_10
    - binutils_impl_linux-64 2.40 h5293946_0
    - binutils_linux-64 2.40.0 hc2dff05_1
    - cmake-no-system 3.25.3 h6a678d5_0
    - gcc_impl_linux-64 11.2.0 h1234567_1
    - gcc_linux-64 11.2.0 h5c386dc_1
    - gxx_impl_linux-64 11.2.0 h1234567_1
    - gxx_linux-64 11.2.0 hc2dff05_1
    - kernel-headers_linux-64 3.10.0 h57e8cba_10
    - ld_impl_linux-64 2.40 h12ee557_0
    - libgcc-devel_linux-64 11.2.0 h1234567_1
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-devel_linux-64 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - make 4.2.1 h1bed415_1
    - ninja-base 1.10.2 hd09550d_5
    - patch 2.7.6 h7b6447c_1001
    - sysroot_linux-64 2.17 h57e8cba_10
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - lz4-c 1.9.4 h6a678d5_1
    - xz 5.4.6 h5eee18b_1
    - zlib 1.2.13 h5eee18b_1
  run:
    - libgcc-ng >=11.2.0
    - libstdcxx-ng >=11.2.0
    - lz4-c >=1.9.4,<1.10.0a0
    - xz >=5.4.6,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - zstd -be -i5
    - test -f ${PREFIX}/include/zstd.h
    - test -f ${PREFIX}/lib/libzstd.a
    - test -f ${PREFIX}/lib/libzstd.so
    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig
    - test -f ${PREFIX}/lib/pkgconfig/libzstd.pc
    - pkg-config --cflags libzstd
  requires:
    - pkg-config
about:
  description: 'Zstandard is a real-time compression algorithm, providing high compression

    ratios. It offers a very wide range of compression / speed trade-off, while

    being backed by a very fast decoder. It also offers a special mode for

    small data, called dictionary compression, and can create dictionaries from

    any sample set. Zstandard library is provided as open source software using

    a BSD license.

    '
  dev_url: https://github.com/facebook/zstd
  doc_url: https://facebook.github.io/zstd/zstd_manual.html
  home: https://facebook.github.io/zstd/
  license: BSD-3-Clause AND GPL-2.0-or-later
  license_family: BSD
  license_file: LICENSE
  summary: Zstandard - Fast real-time compression algorithm
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a3277a64-5e9c-4196-8b60-ad5194832835
  recipe-maintainers:
    - chenghlee
    - msarahan
    - rmax
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/zstd-feedstock.git
  sha: 0bec3d8794a5154155101d8f1bb2f7e4cae0ba0d
